## To build and run the image run:
## docker compose up -d
version: '3.8'
services:
  jupyterhub:
    build: . # hier wird das Dockerfile verwendet
    image: v3inberlin_jupyterhub
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jupyterhub_data:/srv/jupyterhub/data
      - ./jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py

      ## und weitere Verzeichnisse nach notebook_dir
      #- /home/intrepid-ibex/2bhCode/dockerJupyterServer/coding-akademie-python-crashkurs /home/jovyan/work/readonly
      ## einhängen
    ports:
      - "8000:8000"
    networks:
      - jupyterhub
# c.DockerSpawner.network_name

volumes:
  jupyterhub_data:

networks:
  jupyterhub:
    name: jupyterhub

# docker-compose up -d # ausführen um den JupyterHub-Server zu starten

